version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - 9870:9870
    environment:
      - CLUSTER_NAME=stock_cluster
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020       
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop
    deploy:
      replicas: 4

  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - hadoop

  spark-worker:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - hadoop
    deploy:
      replicas: 4

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.2.1
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop:
